### ISSUE TITLE
Define data & data approach

### ISSUE THREAD

**Issue by gabrieltorresgamez** [CryptoFraudDetection/main#12]
- [x] Which data do we want to use?

Talk to Fernando:
- [x] How to get data
- [x] How to combine with wdb

Talk to Moritz:
- [ ] Datasplitting
- [ ] Defining Fraud

Talk to Michael:
- [ ] How to combine with san

**Comment by nod0n** [comment]
has been discussed in https://github.com/orgs/CryptoFraudDetection/discussions/15 and fernando accepted the idea.

**Comment by nod0n** [comment]
discuss with fernando:
- stay logged in
- rate limit strategies
